services:
  - type: web
    name: smartinvoice-api
    env: docker
    rootDir: backend
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    autoDeploy: true
    plan: free
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: Jwt__Issuer
        value: SmartInvoice
      - key: Jwt__Audience
        value: SmartInvoiceClient
      - key: ConnectionStrings__DefaultConnection
        sync: false
      - key: Jwt__SecretKey
        sync: false
