/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{html,ts}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        primary: "#0052cb",
        "primary-container": "#1d6af5",
        "primary-fixed": "#dae2ff",
        "primary-fixed-dim": "#b2c5ff",
        "on-primary": "#ffffff",
        "on-primary-fixed": "#001848",
        "on-primary-container": "#fbf9ff",
        "inverse-primary": "#b2c5ff",
        secondary: "#505f76",
        "secondary-container": "#d0e1fb",
        "secondary-fixed": "#d3e4fe",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#54647a",
        tertiary: "#9e3a00",
        "tertiary-container": "#c74b00",
        "tertiary-fixed": "#ffdbcd",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#fff9f8",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        surface: "#faf8ff",
        "surface-dim": "#d8d9e5",
        "surface-bright": "#faf8ff",
        "surface-variant": "#e1e2ed",
        "surface-container": "#ecedf9",
        "surface-container-low": "#f2f3ff",
        "surface-container-high": "#e7e7f3",
        "surface-container-highest": "#e1e2ed",
        "surface-container-lowest": "#ffffff",
        "surface-tint": "#0055d3",
        "on-surface": "#191b24",
        "on-surface-variant": "#424655",
        "inverse-surface": "#2e3039",
        "inverse-on-surface": "#eff0fc",
        background: "#faf8ff",
        "on-background": "#191b24",
        outline: "#737686",
        "outline-variant": "#c2c6d7",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
      },
      fontSize: {
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        h1: [
          "32px",
          { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "label-md": ["14px", { lineHeight: "20px", fontWeight: "600" }],
        "label-sm": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" },
        ],
        "mono-num": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        h2: [
          "24px",
          { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        h3: ["20px", { lineHeight: "28px", fontWeight: "600" }],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
  // Disable Tailwind's base reset to prevent conflicts with Angular Material
  corePlugins: {
    preflight: false,
  },
};
